[package]
name = "therm"
version = "0.1.0"
edition = "2021"

[profile.release]
strip = true
lto = true
codegen-units = 1
panic = "abort"

[dependencies]
bevy = "0.11"
bevy_xpbd_2d = "0.2"
rand = "0.8"
bevy_prototype_lyon = "0.9"